# Generated by Django 5.2.1 on 2026-01-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Номер телефона для связи', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(help_text='Email адрес для связи', max_length=50, verbose_name='Email')),
                ('whats_app', models.CharField(blank=True, help_text='Ссылка или номер WhatsApp', max_length=100, verbose_name='WhatsApp')),
                ('telegram', models.CharField(blank=True, help_text='Ссылка или username Telegram', max_length=100, verbose_name='Telegram')),
                ('ruk_fio', models.CharField(help_text='Полное имя руководителя', max_length=300, verbose_name='ФИО руководителя')),
                ('inn', models.CharField(help_text='Идентификационный номер налогоплательщика', max_length=50, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
                'db_table': 'site_settings',
            },
        ),
    ]
