# Generated by Django 5.2.1 on 2026-01-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Номер телефона для связи', max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(help_text='Email адрес для связи', max_length=50, verbose_name='Почта')),
                ('whatsapp_link', models.CharField(blank=True, help_text='Ссылка на WhatsApp', max_length=200, verbose_name='Ссылка на WhatsApp')),
                ('telegram_link', models.CharField(blank=True, help_text='Ссылка на Telegram', max_length=200, verbose_name='Ссылка на Telegram')),
                ('footer_description', models.TextField(blank=True, help_text='Описание в подвале сайта', verbose_name='Футер описание')),
                ('footer_org_info', models.TextField(blank=True, help_text='Организационная информация в подвале сайта', verbose_name='Футер орг инфо')),
            ],
            options={
                'verbose_name': 'Основные настройки',
                'verbose_name_plural': 'Основные настройки',
                'db_table': 'main_settings',
            },
        ),
        migrations.RenameModel(
            old_name='SiteSettings',
            new_name='ContactsSettings',
        ),
        migrations.AlterModelOptions(
            name='contactssettings',
            options={'verbose_name': 'Настройки контактов', 'verbose_name_plural': 'Настройки контактов'},
        ),
        migrations.AlterModelTable(
            name='contactssettings',
            table='contacts_settings',
        ),
    ]
