# Generated by Django 5.2.1 on 2026-02-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_mainsettings_rename_sitesettings_contactssettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='display_phone',
            field=models.CharField(blank=True, help_text='Номер телефона для отображения на сайте', max_length=50, verbose_name='Отображаемый номер телефона'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='footer_inn',
            field=models.CharField(blank=True, help_text='ИНН для отображения в подвале сайта', max_length=50, verbose_name='ИНН в футере'),
        ),
    ]
