# Generated by Django 5.2.1 on 2026-02-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_mainsettings_display_phone_mainsettings_footer_inn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactssettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactssettings',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactssettings',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='contactssettings',
            name='whats_app',
        ),
        migrations.RemoveField(
            model_name='mainsettings',
            name='footer_description',
        ),
        migrations.RemoveField(
            model_name='mainsettings',
            name='footer_inn',
        ),
        migrations.RemoveField(
            model_name='mainsettings',
            name='footer_org_info',
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='description',
            field=models.TextField(default='-', help_text='Описание организации', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='info_name',
            field=models.TextField(blank=True, help_text='Организационная информация', verbose_name='Info name'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='inn',
            field=models.CharField(blank=True, help_text='ИНН для отображения', max_length=50, verbose_name='ИНН'),
        ),
    ]
