# Generated by Django 5.2.1 on 2026-02-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_remove_contactssettings_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactssettings',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='contactssettings',
            name='ruk_fio',
        ),
        migrations.RemoveField(
            model_name='mainsettings',
            name='info_name',
        ),
        migrations.AddField(
            model_name='contactssettings',
            name='legal_address',
            field=models.CharField(blank=True, help_text='Юридический адрес организации', max_length=500, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='contactssettings',
            name='ogrn',
            field=models.CharField(blank=True, help_text='Основной государственный регистрационный номер', max_length=20, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='org_name',
            field=models.TextField(blank=True, help_text='Название оргинизации', verbose_name='Info name'),
        ),
    ]
