# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_remove_contactssettings_inn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactssettings',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта', help_text='Широта (latitude) для карты'),
        ),
        migrations.AddField(
            model_name='contactssettings',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота', help_text='Долгота (longitude) для карты'),
        ),
        migrations.AddField(
            model_name='contactssettings',
            name='sales_center_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес офиса продаж', help_text='Адрес центра продаж'),
        ),
    ]
