# Generated by Django 5.2.1 on 2026-02-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_contactssettings_latitude_contactssettings_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsettings',
            name='org_name',
            field=models.TextField(blank=True, help_text='Название организации', verbose_name='Info name'),
        ),
    ]
