# Generated by Django 5.2.1 on 2026-03-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_rename_whatsapp_link_to_max_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsettings',
            name='max_link',
            field=models.CharField(blank=True, help_text='Ссылка на мессенджер Макс', max_length=200, verbose_name='Ссылка на Макс'),
        ),
    ]
