# Generated by Django 5.2.1 on 2026-04-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_alter_mainsettings_max_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='cases',
            field=models.JSONField(blank=True, default=list, help_text='JSON-массив элементов для раздела «Кейсы» (например, [{"title": "...", "body": "..."}])', verbose_name='Кейсы'),
        ),
    ]
