# Generated by Django 5.2.1 on 2026-04-01 23:22

import apps.site_settings.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_main_settings_cases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsettings',
            name='cases',
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='cases_pdf',
            field=models.FileField(blank=True, help_text='PDF-файл с кейсами для раздела «Кейсы»', null=True, upload_to=apps.site_settings.models.main_settings_cases_pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Кейсы (PDF)'),
        ),
    ]
