# Generated by Django 5.2.1 on 2026-04-03 12:51

import apps.site_settings.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_main_settings_cases_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_1', models.FileField(blank=True, help_text='Первый PDF для страницы инвесторов', null=True, upload_to=apps.site_settings.models.investor_settings_pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Документ 1 (PDF)')),
                ('document_2', models.FileField(blank=True, help_text='Второй PDF для страницы инвесторов', null=True, upload_to=apps.site_settings.models.investor_settings_pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Документ 2 (PDF)')),
                ('document_3', models.FileField(blank=True, help_text='Третий PDF для страницы инвесторов', null=True, upload_to=apps.site_settings.models.investor_settings_pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Документ 3 (PDF)')),
            ],
            options={
                'verbose_name': 'Настройки для инвесторов',
                'verbose_name_plural': 'Настройки для инвесторов',
                'db_table': 'investor_settings',
            },
        ),
    ]
