# Generated by Django 5.2.1 on 2026-04-30 20:58

import apps.site_settings.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0012_investor_settings_pdfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='oplata_pdf',
            field=models.FileField(blank=True, help_text='PDF сохраняется в media/documents/oplata.pdf. В API /main-info — путь /oplata.pdf (на проде nginx отдаёт файл по короткому URL).', null=True, upload_to=apps.site_settings.models.main_settings_document_oplata_pdf_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Бронирование и оплата, правила возврата'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='privacy_pdf',
            field=models.FileField(blank=True, help_text='PDF сохраняется в media/documents/privacy.pdf. В API /main-info — путь /privacy.pdf (на проде nginx отдаёт файл по короткому URL).', null=True, upload_to=apps.site_settings.models.main_settings_document_privacy_pdf_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Политика обработки персональных данных и конфиденциальность'),
        ),
    ]
