# Generated by Django 5.2.1 on 2026-05-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0013_mainsettings_privacy_oplata_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_link', models.CharField(blank=True, help_text='Ссылка на таблицу комиссий для агентов', max_length=500, verbose_name='Ссылка на таблицу')),
            ],
            options={
                'verbose_name': 'Настройки для агентов',
                'verbose_name_plural': 'Настройки для агентов',
                'db_table': 'agent_settings',
            },
        ),
    ]
