# Generated by Django 5.2.1 on 2026-09-08 21:10

import apps.site_settings.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0014_agent_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettings',
            name='dealer_advantages',
            field=models.TextField(blank=True, help_text='Один пункт на строку. Пустые строки игнорируются.', verbose_name='Преимущества дилера'),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='dealer_duties',
            field=models.TextField(blank=True, help_text='Один пункт на строку. Пустые строки игнорируются.', verbose_name='Что нужно делать'),
        ),
        migrations.CreateModel(
            name='AgentPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='ФИО партнёра для карточки', max_length=200, verbose_name='ФИО')),
                ('photo', models.ImageField(blank=True, help_text='Фото партнёра (jpg, png, webp)', null=True, upload_to=apps.site_settings.models.agent_partner_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фото')),
                ('deals_count', models.PositiveIntegerField(default=0, help_text='Число сделок для подписи под ФИО', verbose_name='Количество сделок')),
                ('order', models.PositiveIntegerField(default=1, help_text='Порядок вывода на странице (по возрастанию)', verbose_name='Порядок')),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='site_settings.agentsettings', verbose_name='Настройки для агентов')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'db_table': 'agent_partner',
                'ordering': ['order', 'id'],
            },
        ),
    ]
