# Generated by Django 5.2.1 on 2026-05-18 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('re_objects', '0031_premise_show_rented_button'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Код ссылки')),
                ('contact_phone', models.CharField(max_length=32, verbose_name='Контактный телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('premise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='re_objects.premise', verbose_name='Помещение')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to=settings.AUTH_USER_MODEL, verbose_name='Реферер')),
            ],
            options={
                'verbose_name': 'Реферальная ссылка',
                'verbose_name_plural': 'Реферальные ссылки',
                'db_table': 'referrals_referral_link',
                'ordering': ['-created_at'],
            },
        ),
    ]
