"""
Общие схемы для API, включая формат ошибок RFC 7807.
"""
from ninja import Schema
from typing import Optional
from enum import Enum


class ErrorCode(str, Enum):
    """
    Enum для кодов ошибок API.
    
    Все коды ошибок должны быть определены здесь.
    """
    # Accounts errors
    ACCOUNTS_INVALID_CREDENTIALS = "ACCOUNTS_INVALID_CREDENTIALS"
    ACCOUNTS_EMAIL_EXISTS = "ACCOUNTS_EMAIL_EXISTS"
    ACCOUNTS_PHONE_EXISTS = "ACCOUNTS_PHONE_EXISTS"
    ACCOUNTS_PASSWORD_MISMATCH = "ACCOUNTS_PASSWORD_MISMATCH"
    ACCOUNTS_PASSWORD_VALIDATION_FAILED = "ACCOUNTS_PASSWORD_VALIDATION_FAILED"
    ACCOUNTS_INVALID_USER_TYPE = "ACCOUNTS_INVALID_USER_TYPE"
    ACCOUNTS_MISSING_ORGANIZATION_NAME = "ACCOUNTS_MISSING_ORGANIZATION_NAME"
    ACCOUNTS_MISSING_INN = "ACCOUNTS_MISSING_INN"
    ACCOUNTS_UNAUTHORIZED = "ACCOUNTS_UNAUTHORIZED"
    ACCOUNTS_TOKEN_EXPIRED = "ACCOUNTS_TOKEN_EXPIRED"
    ACCOUNTS_INVALID_TOKEN = "ACCOUNTS_INVALID_TOKEN"
    ACCOUNTS_NO_REFRESH_TOKEN = "ACCOUNTS_NO_REFRESH_TOKEN"
    ACCOUNTS_USER_NOT_FOUND = "ACCOUNTS_USER_NOT_FOUND"
    ACCOUNTS_EMAIL_ALREADY_USED = "ACCOUNTS_EMAIL_ALREADY_USED"
    ACCOUNTS_PHONE_ALREADY_USED = "ACCOUNTS_PHONE_ALREADY_USED"
    ACCOUNTS_INVALID_CURRENT_PASSWORD = "ACCOUNTS_INVALID_CURRENT_PASSWORD"
    ACCOUNTS_REGISTRATION_ERROR = "ACCOUNTS_REGISTRATION_ERROR"
    ACCOUNTS_LOGIN_ERROR = "ACCOUNTS_LOGIN_ERROR"
    ACCOUNTS_PASSWORD_RESET_ERROR = "ACCOUNTS_PASSWORD_RESET_ERROR"
    ACCOUNTS_PASSWORD_RESET_TOKEN_INVALID = "ACCOUNTS_PASSWORD_RESET_TOKEN_INVALID"
    ACCOUNTS_PASSWORD_RESET_TOKEN_EXPIRED = "ACCOUNTS_PASSWORD_RESET_TOKEN_EXPIRED"
    
    # Feedback errors
    FEEDBACK_NOT_FOUND = "FEEDBACK_NOT_FOUND"
    FEEDBACK_CREATION_ERROR = "FEEDBACK_CREATION_ERROR"
    FEEDBACK_UPDATE_ERROR = "FEEDBACK_UPDATE_ERROR"
    FEEDBACK_DELETE_ERROR = "FEEDBACK_DELETE_ERROR"
    FEEDBACK_VALIDATION_ERROR = "FEEDBACK_VALIDATION_ERROR"
    
    # Site settings errors
    SITE_SETTINGS_NOT_FOUND = "SITE_SETTINGS_NOT_FOUND"
    SITE_SETTINGS_ERROR = "SITE_SETTINGS_ERROR"

    # Re objects (premises)
    RE_OBJECTS_NOT_FOUND = "RE_OBJECTS_NOT_FOUND"


class ProblemDetail(Schema):
    """
    Формат ошибок по RFC 7807 (Problem Details for HTTP APIs).
    
    Используется для стандартизации всех ошибок API.
    """
    type: str  # URI типа ошибки
    status: int  # HTTP статус код
    title: str  # Краткое описание ошибки
    detail: str  # Детальное описание ошибки
    instance: Optional[str] = None  # URI ресурса, на котором произошла ошибка
    code: ErrorCode  # Внутренний код ошибки для фронтенда (enum)
