# Generated by Django 5.2.1 on 2026-05-17 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('payments', '0002_alter_payment_options_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source_payment',
            field=models.ForeignKey(blank=True, help_text='Заполняется при автоматическом создании брони после успешной оплаты (продажа)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to='payments.payment', verbose_name='Платёж, создавший бронь'),
        ),
    ]
