# Generated by Django 5.2.1 on 2026-01-31 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название города (например, Казань)', max_length=200, verbose_name='Название города')),
                ('is_default', models.BooleanField(default=False, help_text='Использовать как город по умолчанию', verbose_name='Город по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 're_cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название региона (например, Татарстан)', max_length=200, unique=True, verbose_name='Название региона')),
                ('code', models.CharField(blank=True, help_text='Код региона (опционально)', max_length=20, null=True, unique=True, verbose_name='Код региона')),
                ('is_default', models.BooleanField(default=False, help_text='Использовать как регион по умолчанию', verbose_name='Регион по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 're_regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название или адрес здания', max_length=300, verbose_name='Название здания')),
                ('address', models.CharField(help_text='Полный адрес здания', max_length=500, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, help_text='Описание здания, особенности', verbose_name='Описание')),
                ('total_floors', models.PositiveIntegerField(blank=True, help_text='Общее количество этажей в здании', null=True, verbose_name='Количество этажей')),
                ('year_built', models.PositiveIntegerField(blank=True, help_text='Год постройки здания', null=True, verbose_name='Год постройки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(help_text='Город, в котором находится здание', on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='re_objects.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
                'db_table': 're_buildings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Номер этажа (может быть отрицательным для подвалов)', verbose_name='Номер этажа')),
                ('description', models.CharField(blank=True, help_text="Описание этажа (например, 'Офисный этаж')", max_length=500, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(help_text='Здание, к которому относится этаж', on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='re_objects.building', verbose_name='Здание')),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
                'db_table': 're_floors',
                'ordering': ['building', 'number'],
                'unique_together': {('building', 'number')},
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(help_text='Регион, к которому относится город', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='re_objects.region', verbose_name='Регион'),
        ),
        migrations.CreateModel(
            name='Premise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, help_text='Площадь помещения в квадратных метрах', max_digits=10, verbose_name='Площадь, м²')),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость аренды за месяц в рублях', max_digits=12, null=True, verbose_name='Цена аренды в месяц, ₽')),
                ('price_per_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость аренды за квадратный метр', max_digits=10, null=True, verbose_name='Цена за м², ₽')),
                ('premise_type', models.CharField(choices=[('office', 'Офис'), ('other', 'Другое')], default='office', help_text='Тип помещения (офис, торговое и т.д.)', max_length=50, verbose_name='Тип помещения')),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('reserved', 'Зарезервировано'), ('rented', 'Сдано'), ('unavailable', 'Недоступно')], default='available', help_text='Статус доступности помещения', max_length=20, verbose_name='Статус')),
                ('number', models.CharField(blank=True, help_text='Номер или название помещения', max_length=50, verbose_name='Номер помещения')),
                ('description', models.TextField(blank=True, help_text='Подробное описание помещения', verbose_name='Описание')),
                ('ceiling_height', models.DecimalField(blank=True, decimal_places=2, help_text='Высота потолков в метрах', max_digits=5, null=True, verbose_name='Высота потолков, м')),
                ('has_windows', models.BooleanField(default=True, help_text='Наличие окон в помещении', verbose_name='Есть окна')),
                ('has_parking', models.BooleanField(default=False, help_text='Наличие парковки', verbose_name='Есть парковка')),
                ('is_furnished', models.BooleanField(default=False, help_text='Помещение с мебелью', verbose_name='С мебелью')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(help_text='Город, в котором находится помещение (для быстрого поиска)', on_delete=django.db.models.deletion.CASCADE, related_name='premises', to='re_objects.city', verbose_name='Город')),
                ('floor', models.ForeignKey(blank=True, help_text='Этаж, на котором находится помещение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premises', to='re_objects.floor', verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'db_table': 're_premises',
                'ordering': ['city', 'floor__building', 'floor', 'number'],
                'indexes': [models.Index(fields=['city', 'status'], name='re_premises_city_id_5b6233_idx'), models.Index(fields=['city', 'premise_type'], name='re_premises_city_id_579f6e_idx'), models.Index(fields=['area'], name='re_premises_area_16c4b5_idx'), models.Index(fields=['price_per_month'], name='re_premises_price_p_8e344e_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'region')},
        ),
    ]
