# Generated by Django 5.2.1 on 2026-01-31 13:59

import apps.re_objects.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Название медиафайла', max_length=200, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (0 - первый)', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(help_text='Изображение здания', upload_to=apps.re_objects.models.building_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Изображение')),
                ('category', models.CharField(blank=True, help_text="Категория изображения (например, 'фасад', 'интерьер', 'планировка')", max_length=100, verbose_name='Категория')),
                ('is_primary', models.BooleanField(default=False, help_text='Использовать как основное изображение здания', verbose_name='Основное изображение')),
                ('building', models.ForeignKey(help_text='Здание, к которому относится изображение', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='re_objects.building', verbose_name='Здание')),
            ],
            options={
                'verbose_name': 'Изображение здания',
                'verbose_name_plural': 'Изображения зданий',
                'db_table': 're_building_images',
                'ordering': ['building', 'order', 'created_at'],
                'indexes': [models.Index(fields=['building', 'is_primary'], name='re_building_buildin_d8a679_idx'), models.Index(fields=['building', 'category'], name='re_building_buildin_03955d_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuildingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Название медиафайла', max_length=200, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (0 - первый)', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Видео файл здания', upload_to=apps.re_objects.models.building_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])], verbose_name='Видео')),
                ('category', models.CharField(blank=True, help_text="Категория видео (например, 'тур', 'обзор', 'презентация')", max_length=100, verbose_name='Категория')),
                ('building', models.ForeignKey(help_text='Здание, к которому относится видео', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='re_objects.building', verbose_name='Здание')),
            ],
            options={
                'verbose_name': 'Видео здания',
                'verbose_name_plural': 'Видео зданий',
                'db_table': 're_building_videos',
                'ordering': ['building', 'order', 'created_at'],
                'indexes': [models.Index(fields=['building', 'category'], name='re_building_buildin_4a0e8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PremiseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Название медиафайла', max_length=200, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (0 - первый)', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(help_text='Изображение помещения', upload_to=apps.re_objects.models.premise_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Изображение')),
                ('is_primary', models.BooleanField(default=False, help_text='Использовать как основное изображение помещения', verbose_name='Основное изображение')),
                ('premise', models.ForeignKey(help_text='Помещение, к которому относится изображение', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='re_objects.premise', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Изображение помещения',
                'verbose_name_plural': 'Изображения помещений',
                'db_table': 're_premise_images',
                'ordering': ['premise', 'order', 'created_at'],
                'indexes': [models.Index(fields=['premise', 'is_primary'], name='re_premise__premise_bdd6c8_idx')],
            },
        ),
    ]
