# Generated by Django 5.2.1 on 2026-01-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0002_buildingimage_buildingvideo_premiseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingimage',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Порядок отображения (1 - первый)', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='buildingvideo',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Порядок отображения (1 - первый)', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Стоимость аренды за месяц в рублях', max_digits=12, verbose_name='Цена аренды в месяц, ₽'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='premise',
            name='price_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Стоимость аренды за квадратный метр (вычисляется автоматически при сохранении)', max_digits=10, null=True, verbose_name='Цена за м², ₽'),
        ),
        migrations.AlterField(
            model_name='premiseimage',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Порядок отображения (1 - первый)', verbose_name='Порядок'),
        ),
        migrations.AlterUniqueTogether(
            name='buildingimage',
            unique_together={('building', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='buildingvideo',
            unique_together={('building', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='premiseimage',
            unique_together={('premise', 'order')},
        ),
    ]
