# Generated by Django 5.2.1 on 2026-01-31 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0003_alter_buildingimage_order_alter_buildingvideo_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Город, в котором находится помещение (для быстрого поиска). Если не указан, будет использован город по умолчанию.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premises', to='re_objects.city', verbose_name='Город'),
        ),
    ]
