# Generated by Django 5.2.1 on 2026-01-31 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0004_alter_premise_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buildingimage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='buildingvideo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='premiseimage',
            unique_together=set(),
        ),
    ]
