# Generated by Django 5.2.1

from django.db import migrations, models
import django.db.models.deletion


def backfill_building_from_floor(apps, schema_editor):
    """Заполняем building из этажа для существующих помещений."""
    Premise = apps.get_model('re_objects', 'Premise')
    Floor = apps.get_model('re_objects', 'Floor')
    for p in Premise.objects.filter(floor_id__isnull=False):
        floor = Floor.objects.filter(pk=p.floor_id).first()
        if floor:
            p.building_id = floor.building_id
            p.save(update_fields=['building_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0005_alter_buildingimage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premise',
            name='building',
            field=models.ForeignKey(
                blank=True,
                help_text='Здание, в котором находится помещение',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='premises',
                to='re_objects.building',
                verbose_name='Здание'
            ),
        ),
        migrations.RunPython(backfill_building_from_floor, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='premise',
            name='floor',
            field=models.ForeignKey(
                blank=True,
                help_text='Этаж, на котором находится помещение (должен относиться к выбранному зданию)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='premises',
                to='re_objects.floor',
                verbose_name='Этаж'
            ),
        ),
        migrations.AddIndex(
            model_name='premise',
            index=models.Index(fields=['building'], name='re_premises_building_idx'),
        ),
    ]
