# Generated by Django 5.2.1

from django.db import migrations, models
import django.db.models.deletion


def set_default_building_for_null(apps, schema_editor):
    """Для помещений без здания проставляем первое здание в БД (перед введением NOT NULL)."""
    Premise = apps.get_model('re_objects', 'Premise')
    Building = apps.get_model('re_objects', 'Building')
    first_building = Building.objects.order_by('pk').first()
    if first_building:
        Premise.objects.filter(building_id__isnull=True).update(building_id=first_building.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0006_premise_building'),
    ]

    operations = [
        migrations.RunPython(set_default_building_for_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='premise',
            name='building',
            field=models.ForeignKey(
                help_text='Здание, в котором находится помещение',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='premises',
                to='re_objects.building',
                verbose_name='Здание'
            ),
        ),
    ]
