# Generated by Django 5.2.1 on 2026-02-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0007_premise_building_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premise',
            options={'ordering': ['city', 'building', 'floor', 'number'], 'verbose_name': 'Помещение', 'verbose_name_plural': 'Помещения'},
        ),
        migrations.RenameIndex(
            model_name='premise',
            new_name='re_premises_buildin_c4a16a_idx',
            old_name='re_premises_building_idx',
        ),
    ]
