# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0008_alter_premise_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premise',
            name='available_for_rent',
            field=models.BooleanField(default=True, help_text='Помещение предлагается в аренду', verbose_name='Доступно для аренды'),
        ),
        migrations.AddField(
            model_name='premise',
            name='available_for_sale',
            field=models.BooleanField(default=False, help_text='Помещение предлагается к продаже', verbose_name='Доступно для продажи'),
        ),
    ]
