# Generated by Django 5.2.1

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("re_objects", "0009_premise_available_for_rent_available_for_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="premise",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Публичный идентификатор помещения для API и URL",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
