# Generated by Django 5.2.1

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("re_objects", "0010_premise_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Публичный идентификатор здания для API",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
