# Generated by Django 5.2.1

import uuid
from django.db import migrations, models


def populate_building_uuids(apps, schema_editor):
    """Заполняет уникальные UUID для существующих записей Building."""
    Building = apps.get_model("re_objects", "Building")
    for building in Building.objects.all():
        building.uuid = uuid.uuid4()
        building.save(update_fields=["uuid"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("re_objects", "0010_premise_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                editable=False,
                help_text="Публичный идентификатор здания для API",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.RunPython(populate_building_uuids, noop_reverse),
        migrations.AlterField(
            model_name="building",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Публичный идентификатор здания для API",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
