# Generated by Django 5.2.1 on 2026-03-01 18:02

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0011_building_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='floor',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='building', chained_model_field='building', help_text='Этаж, на котором находится помещение (должен относиться к выбранному зданию)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premises', to='re_objects.floor', verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='price_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость аренды за квадратный метр. Задаётся вручную.', max_digits=10, null=True, verbose_name='Цена за м², ₽'),
        ),
    ]
