# Generated by Django 5.2.1 on 2026-03-09 13:18

import apps.re_objects.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0012_alter_premise_floor_alter_premise_price_per_sqm'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='schema_svg',
            field=models.FileField(blank=True, help_text='Файл схемы этажа в формате SVG', null=True, upload_to=apps.re_objects.models.floor_schema_svg_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='SVG-схема этажа'),
        ),
    ]
