# Generated by Django 5.2.1 on 2026-03-25 22:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0014_premise_human_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='human_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Кэш итоговой стоимости продажи и аренды за месяц — чтобы не пересчитывать при агрегации по зданиям и при выгрузке. Пересчитывается при сохранении: при продаже — итог продажи (price_per_month если > 0, иначе площадь × price_per_sqm); при аренде без продажи — цена за месяц; иначе 0.', max_digits=12, verbose_name='Итоговая стоимость продажи (кэш), ₽'),
        ),
    ]
