# Generated by Django 5.2.1 on 2026-03-28 15:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0015_alter_premise_human_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Географическая широта (WGS-84), от −90 до 90', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Географическая долгота (WGS-84), от −180 до 180', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='Долгота'),
        ),
    ]
