# Generated by Django 5.2.1 on 2026-03-28 16:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0016_building_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='human_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Денормализованное значение для агрегатов и выгрузки. Пересчитывается при сохранении: при продаже — итог (price_per_month если > 0, иначе площадь × price_per_sqm); при аренде без продажи — цена за месяц; иначе 0.', max_digits=12, verbose_name='Итоговая стоимость продажи, ₽'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='price_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость продажи за квадратный метр. Обязательна, если помещение доступно для продажи.', max_digits=10, null=True, verbose_name='Цена продажи за м², ₽'),
        ),
    ]
