# Generated by Django 5.2.1 on 2026-03-28 17:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0017_premise_price_validation_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='human_price',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0'),
                help_text='Площадь × цена продажи за м². Пересчитывается при каждом сохранении. ',
                max_digits=12,
                verbose_name='Итоговая стоимость продажи, ₽',
            ),
        ),
    ]
