# Generated by Django 5.2.1 on 2026-03-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0018_premise_human_price_sale_from_sqm_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='human_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Площадь × цена продажи за м². Пересчитывается при каждом сохранении. ',
                max_digits=12,
                null=True,
                verbose_name='Итоговая стоимость продажи, ₽',
            ),
        ),
    ]
