# Generated by Django 5.2.1 on 2026-03-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0019_premise_human_price_nullable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premise',
            old_name='human_price',
            new_name='full_sell_price',
        ),
        migrations.AlterField(
            model_name='premise',
            name='full_sell_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Площадь × цена продажи за м². Пересчитывается при каждом сохранении. ',
                max_digits=12,
                null=True,
                verbose_name='Итоговая стоимость продажи, ₽',
            ),
        ),
    ]
