# Generated by Django 5.2.1 on 2026-04-01 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0020_rename_human_price_to_full_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='floor',
            field=models.ForeignKey(blank=True, help_text='Этаж, на котором находится помещение (должен относиться к выбранному зданию)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premises', to='re_objects.floor', verbose_name='Этаж'),
        ),
    ]
