# Generated by Django 5.2.1 on 2026-04-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0021_premise_floor_plain_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость аренды за месяц в рублях (необязательно)', max_digits=12, null=True, verbose_name='Цена аренды в месяц, ₽'),
        ),
    ]
