# Generated by Django 5.2.1 on 2026-04-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0022_premise_price_per_month_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='full_sell_price',
            field=models.PositiveBigIntegerField(blank=True, help_text='Площадь × цена продажи за м² в целых рублях. Пересчитывается при каждом сохранении.', null=True, verbose_name='Итоговая стоимость продажи, ₽'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='price_per_month',
            field=models.PositiveBigIntegerField(blank=True, help_text='Стоимость аренды за месяц в целых рублях (необязательно)', null=True, verbose_name='Цена аренды в месяц, ₽'),
        ),
        migrations.AlterField(
            model_name='premise',
            name='price_per_sqm',
            field=models.PositiveBigIntegerField(blank=True, help_text='Стоимость продажи за м² в целых рублях. Обязательна, если помещение доступно для продажи.', null=True, verbose_name='Цена продажи за м², ₽'),
        ),
    ]
