# Generated by Django 5.2.1 on 2026-04-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0023_premise_prices_integer'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='premise',
            name='re_premises_city_id_5b6233_idx',
        ),
        migrations.RemoveField(
            model_name='premise',
            name='status',
        ),
    ]
