# Generated by Django 5.2.1 on 2026-04-11 13:59

import apps.re_objects.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0025_media_original_card_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingimage',
            name='original',
            field=models.ImageField(help_text='Исходный файл; card и detail генерируются автоматически', upload_to=apps.re_objects.models.building_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Оригинал'),
        ),
        migrations.AlterField(
            model_name='buildingvideo',
            name='file',
            field=models.FileField(help_text='Оригинальный видеофайл', upload_to=apps.re_objects.models.building_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])], verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='premiseimage',
            name='original',
            field=models.ImageField(help_text='Исходный файл (jpg/png/webp/gif); card и detail генерируются автоматически', upload_to=apps.re_objects.models.premise_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Оригинал'),
        ),
    ]
