# Generated by Django 5.2.1 on 2026-04-11 14:32

import apps.re_objects.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0026_alter_media_field_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingimage',
            name='card',
            field=models.ImageField(blank=True, help_text='WebP, вписано в 560×300 без обрезки', null=True, upload_to=apps.re_objects.models.building_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webp'])], verbose_name='Превью карточки'),
        ),
        migrations.AlterField(
            model_name='buildingvideo',
            name='card',
            field=models.ImageField(blank=True, help_text='WebP с первого кадра (ffmpeg), вписано в 560×300 без обрезки', null=True, upload_to=apps.re_objects.models.building_video_card_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webp'])], verbose_name='Превью карточки'),
        ),
        migrations.AlterField(
            model_name='premiseimage',
            name='card',
            field=models.ImageField(blank=True, help_text='WebP, вписано в 560×300 без обрезки (пропорции сохраняются)', null=True, upload_to=apps.re_objects.models.premise_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webp'])], verbose_name='Превью карточки'),
        ),
    ]
