# Generated by Django 5.2.1 on 2026-04-29 20:14

from django.db import migrations, models


def forwards_fill_room_number(apps, schema_editor):
    """Бывшее поле number стало title; дублируем в room_number для схемы этажа и того же отображения."""
    Premise = apps.get_model('re_objects', 'Premise')
    for p in Premise.objects.all():
        val = (getattr(p, 'title', None) or '')[:50]
        if val:
            Premise.objects.filter(pk=p.pk).update(room_number=val)


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0027_alter_card_help_contain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premise',
            options={
                'ordering': ['city', 'building', 'floor', 'room_number', 'title'],
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
        migrations.AddField(
            model_name='premise',
            name='room_number',
            field=models.CharField(
                blank=True,
                help_text='Номер помещения (для схемы этажа и идентификации)',
                max_length=50,
                verbose_name='Номер помещения',
            ),
        ),
        migrations.RenameField(
            model_name='premise',
            old_name='number',
            new_name='title',
        ),
        migrations.RunPython(forwards_fill_room_number, migrations.RunPython.noop),
    ]
