# Generated by Django 5.2.1 on 2026-05-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0028_premise_room_number_and_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingimage',
            options={'ordering': ['building', '-is_primary', 'order', 'created_at'], 'verbose_name': 'Изображение здания', 'verbose_name_plural': 'Изображения зданий'},
        ),
        migrations.AlterModelOptions(
            name='premiseimage',
            options={'ordering': ['premise', '-is_primary', 'order', 'created_at'], 'verbose_name': 'Изображение помещения', 'verbose_name_plural': 'Изображения помещений'},
        ),
        migrations.AlterField(
            model_name='premise',
            name='title',
            field=models.CharField(blank=True, help_text='Понятное название помещения (по желанию)', max_length=50, verbose_name='Название помещения'),
        ),
    ]
