# Generated by Django 5.2.1 on 2026-05-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0029_alter_buildingimage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='description',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='floor',
            name='title',
            field=models.CharField(
                blank=False,
                help_text="Название этажа (например, 'Офисный этаж')",
                max_length=500,
                verbose_name='Название этажа',
            ),
        ),
    ]
