# Generated by Django 5.2.1 on 2026-05-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0030_remove_floor_description_floor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='premise',
            name='show_rented_button',
            field=models.BooleanField(default=False, help_text='В режиме продажи на схеме этажа выставляет is_occupied=true', verbose_name='Показать кнопку "Сдано"'),
        ),
    ]
