# Generated by Django 5.2.1 on 2026-06-16 21:18

import apps.re_objects.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0031_premise_show_rented_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='premise',
            name='presentation',
            field=models.FileField(blank=True, help_text='PDF, PPT или PPTX', null=True, upload_to=apps.re_objects.models.premise_presentation_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx'])], verbose_name='Презентация'),
        ),
        migrations.CreateModel(
            name='PremiseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Название медиафайла', max_length=200, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=1, help_text='Порядок отображения (1 - первый)', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Оригинальный видеофайл', upload_to=apps.re_objects.models.premise_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])], verbose_name='Видео')),
                ('card', models.ImageField(blank=True, help_text='WebP с первого кадра (ffmpeg), вписано в 560×300 без обрезки', null=True, upload_to=apps.re_objects.models.premise_video_card_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webp'])], verbose_name='Превью карточки')),
                ('premise', models.ForeignKey(help_text='Помещение, к которому относится видео', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='re_objects.premise', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Видео помещения',
                'verbose_name_plural': 'Видео помещений',
                'db_table': 're_premise_videos',
                'ordering': ['premise', 'order', 'created_at'],
                'indexes': [models.Index(fields=['premise'], name='re_premise__premise_cd566e_idx')],
            },
        ),
    ]
