# Generated by Django 5.2.1 on 2026-07-11 20:11

import apps.re_objects.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0031_premise_show_rented_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPanorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.re_objects.models.floor_panorama_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])], verbose_name='Файл панорамы')),
                ('title', models.CharField(blank=True, help_text='Только для админки', max_length=200, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=1, help_text='Порядок комнат в viewer', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='re_objects.floor', verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Панорама этажа',
                'verbose_name_plural': 'Панорамы этажа',
                'db_table': 're_floor_panoramas',
                'ordering': ['floor', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PremisePanorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.re_objects.models.premise_panorama_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])], verbose_name='Файл панорамы')),
                ('title', models.CharField(blank=True, help_text='Только для админки', max_length=200, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=1, help_text='Порядок комнат в viewer', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('premise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='re_objects.premise', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Панорама помещения',
                'verbose_name_plural': 'Панорамы помещения',
                'db_table': 're_premise_panoramas',
                'ordering': ['premise', 'order', 'id'],
            },
        ),
    ]
