# Generated by Django 5.2.1 on 2026-06-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0031_premise_show_rented_button'),
    ]

    operations = []
