# Generated by Django 5.2.1 on 2026-06-24 17:45

import apps.re_objects.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0031_premise_show_rented_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='presentation',
            field=models.FileField(blank=True, help_text='Файл презентации здания (PDF, PPT, PPTX)', null=True, upload_to=apps.re_objects.models.building_presentation_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx'])], verbose_name='Презентация'),
        ),
    ]
