# Generated by Django 5.2.1 on 2026-07-11 20:25

import apps.re_objects.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0032_add_panoramas'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='presentation_rent',
            field=models.FileField(blank=True, help_text='Файл презентации здания для аренды (PDF, PPT, PPTX)', null=True, upload_to=apps.re_objects.models.building_presentation_rent_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx'])], verbose_name='Презентация (аренда)'),
        ),
        migrations.AddField(
            model_name='building',
            name='presentation_sale',
            field=models.FileField(blank=True, help_text='Файл презентации здания для продажи (PDF, PPT, PPTX)', null=True, upload_to=apps.re_objects.models.building_presentation_sale_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx'])], verbose_name='Презентация (продажа)'),
        ),
    ]
