# Generated by Django 5.2.1 on 2026-06-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0032_building_presentation'),
        ('re_objects', '0032_premise_presentation_premisevideo'),
    ]

    operations = [
    ]
