# Generated by Django 5.2.1 on 2026-07-05 10:16

import apps.re_objects.models
import django.core.validators
from django.db import migrations, models


def copy_building_presentation_to_deal_types(apps, schema_editor):
    Building = apps.get_model('re_objects', 'Building')

    for building in Building.objects.exclude(presentation='').exclude(presentation__isnull=True):
        old_presentation = building.presentation
        if old_presentation and not building.presentation_rent:
            building.presentation_rent = old_presentation
        if old_presentation and not building.presentation_sale:
            building.presentation_sale = old_presentation
        building.save(update_fields=['presentation_rent', 'presentation_sale'])


def copy_deal_type_presentation_to_legacy(apps, schema_editor):
    Building = apps.get_model('re_objects', 'Building')

    for building in Building.objects.all():
        fallback_presentation = building.presentation_sale or building.presentation_rent
        if fallback_presentation:
            building.presentation = fallback_presentation
            building.save(update_fields=['presentation'])


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0033_merge_20260624_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='presentation_rent',
            field=models.FileField(blank=True, help_text='Файл презентации здания для аренды (PDF, PPT, PPTX)', null=True, upload_to=apps.re_objects.models.building_presentation_rent_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx'])], verbose_name='Презентация (аренда)'),
        ),
        migrations.AddField(
            model_name='building',
            name='presentation_sale',
            field=models.FileField(blank=True, help_text='Файл презентации здания для продажи (PDF, PPT, PPTX)', null=True, upload_to=apps.re_objects.models.building_presentation_sale_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx'])], verbose_name='Презентация (продажа)'),
        ),
        migrations.RunPython(
            code=copy_building_presentation_to_deal_types,
            reverse_code=copy_deal_type_presentation_to_legacy,
        ),
        migrations.RemoveField(
            model_name='building',
            name='presentation',
        ),
    ]
