# Generated by Django 5.2.1 on 2026-07-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0032_add_panoramas'),
        ('re_objects', '0034_remove_building_presentation_and_more'),
    ]

    operations = [
    ]
