# Generated by Django 5.2.1 on 2026-01-29 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя отправителя', max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(help_text='Email адрес для связи', max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Номер телефона', max_length=20, verbose_name='Телефон')),
                ('subject', models.CharField(help_text='Тема обращения', max_length=200, verbose_name='Тема')),
                ('message', models.TextField(help_text='Текст сообщения', verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('resolved', 'Решена'), ('closed', 'Закрыта')], default='new', help_text='Статус обработки обращения', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'db_table': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
