# Generated by Django 5.2.1 on 2026-04-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('processed', 'Обработано')], default='new', help_text='Статус обработки обращения', max_length=20, verbose_name='Статус'),
        ),
    ]
