# Generated by Django 5.2.1 on 2026-04-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='application_source',
            field=models.CharField(blank=True, default='', help_text='Откуда пришла заявка (страница, кампания, UTM и т.п.)', max_length=255, verbose_name='Источник заявки'),
        ),
    ]
