# Generated by Django 5.2.1 on 2026-04-02 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_status_new_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email адрес для связи', max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Текст сообщения', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(help_text='Номер телефона', max_length=20, verbose_name='Телефон'),
        ),
    ]
