# Generated by Django 5.2.1 on 2026-04-01 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_application_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email (не используется в заявке с сайта, зарезервировано)', max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Текст сообщения (необязательно)', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Тема обращения (не используется в заявке с сайта)', max_length=200, verbose_name='Тема'),
        ),
    ]
