# Generated by Django 5.2.1 on 2026-04-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_email_alter_feedback_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='origin_key',
            field=models.CharField(default='Unknown', help_text='Ключ источника обращения', max_length=200, verbose_name='Ключ источника'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='origin_url',
            field=models.URLField(blank=True, default='', help_text='URL источника обращения', max_length=2000, verbose_name='URL источника'),
        ),
    ]
