# Generated by Django 5.2.1 on 2026-04-04 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('re_objects', '0023_premise_prices_integer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[('rent', 'Аренда'), ('sale', 'Продажа')], max_length=10, verbose_name='Тип сделки')),
                ('rent_expires_at', models.DateTimeField(blank=True, help_text='Для сделок типа «аренда»', null=True, verbose_name='Окончание срока аренды')),
                ('contract_type', models.CharField(blank=True, choices=[('pdkp', 'ПДКП'), ('dkp', 'ДКП')], help_text='Для сделок типа «продажа» (ПДКП / ДКП)', max_length=10, null=True, verbose_name='Тип договора')),
                ('contract_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание договора (продажа)')),
                ('commission_amount', models.PositiveBigIntegerField(blank=True, help_text='Учитывается в ЛК для агентов', null=True, verbose_name='Комиссия, ₽')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('premise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='re_objects.premise', verbose_name='Помещение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'db_table': 'deals_deal',
                'ordering': ['-created_at'],
            },
        ),
    ]
