# Generated by Django 5.2.1 on 2026-04-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='contract_expires_at',
            field=models.DateField(blank=True, help_text='Только дата', null=True, verbose_name='Окончание договора (продажа)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='rent_expires_at',
            field=models.DateField(blank=True, help_text='Для сделок типа «аренда» (только дата)', null=True, verbose_name='Окончание срока аренды'),
        ),
    ]
