# Generated by Django 5.2.1 on 2026-04-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_deal_dates_dateonly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='contract_expires_at',
            new_name='contract_signed_on',
        ),
    ]
