# Generated by Django 5.2.1 on 2026-04-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_deal_commission_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='contract_signed_on',
            field=models.DateField(blank=True, help_text='Для сделок типа «продажа», только дата', null=True, verbose_name='Дата заключения договора'),
        ),
    ]
