# Generated by Django 5.2.1 on 2026-05-10 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('re_objects', '0029_alter_buildingimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_payment_id', models.CharField(max_length=128, unique=True)),
                ('idempotence_key', models.UUIDField(unique=True)),
                ('status', models.CharField(max_length=64)),
                ('paid', models.BooleanField(default=False)),
                ('amount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_currency', models.CharField(max_length=3)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('premise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='re_objects.premise')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
            },
        ),
    ]
