# Generated by Django 5.2.1 on 2026-05-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Платёж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting_for_capture', 'Waiting for capture'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled')], default='pending', max_length=32),
        ),
    ]
