# Generated by Django 5.2.1 on 2026-05-18 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_alter_payment_status'),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='referral_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='referrals.referrallink'),
        ),
    ]
